var child = [
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c0', 'linked': 5, 'url': 'http://localhost:3000/login/', 'fetched': true, 'code': 302, 'len': 27, 'decl_mime': 'text/plain', 'sniff_mime': 'text/plain', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 4, 1, 0, 4, 0 ], 'sig': 0xdf0466f0 },
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c1', 'linked': 2, 'url': 'http://localhost:3000/login/', 'fetched': true, 'code': 200, 'len': 1780, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0x94a32bfa },
  { 'dupe': false, 'type': 4, 'name': 'register', 'dir': 'c4', 'linked': 5, 'url': 'http://localhost:3000/register/', 'fetched': true, 'code': 200, 'len': 2588, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 4, 0, 0, 3, 0 ], 'sig': 0xf6436c08 },
  { 'dupe': false, 'type': 4, 'name': 'stylesheets', 'dir': 'c5', 'linked': 2, 'url': 'http://localhost:3000/stylesheets/', 'fetched': true, 'code': 404, 'len': 1721, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': true, 'csens': true, 'child_cnt': 1, 'issue_cnt': [ 0, 0, 1, 0, 0 ], 'sig': 0x9b9908d },
  { 'dupe': false, 'type': 4, 'name': 'user', 'dir': 'c6', 'linked': 5, 'url': 'http://localhost:3000/user/', 'fetched': true, 'code': 200, 'len': 1553, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 11, 'issue_cnt': [ 10, 3, 1, 4, 0 ], 'sig': 0x40e974da },
  { 'dupe': false, 'type': 8, 'name': 'images', 'dir': 'c7', 'linked': 2, 'url': 'http://localhost:3000/images', 'fetched': true, 'code': 301, 'len': 179, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'UTF-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xfff7ffff },
  { 'dupe': false, 'type': 16, 'name': 'user', 'dir': 'c8', 'linked': 2, 'url': 'http://localhost:3000/user', 'fetched': true, 'code': 302, 'len': 28, 'decl_mime': 'text/plain', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 2, 1, 0, 0, 0 ], 'sig': 0xbdfd51ff },
];
